var_for_docker_image: &docker_image circleci/python:2.7.14-jessie-browsers

anchor_for_job_defaults: &job_defaults
  working_directory: /home/circleci/oppia
  docker:
    - image: *docker_image

anchor_for_installing_dependencies: &install_dependencies
  name: Install dependencies
  command: |
    source scripts/setup.sh || exit 1
    source scripts/setup_gae.sh || exit 1

anchor_for_restoring_cache: &restore_cache
  keys:
    - setup-files-cache-{{ checksum "date" }}
    - third-party-cache-{{ checksum "date" }}

anchor_for_installing_chrome: &install_chrome
  name: Install Chrome
  command: |
    sudo apt-get install lsb-release libappindicator3-1
    curl -L -o google-chrome.deb https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_67.0.3396.99-1_amd64.deb
    sudo dpkg -i google-chrome.deb
    sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
    rm google-chrome.deb

version: 2
jobs:
  setup:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_dependencies
      - save_cache:
          key: setup-files-cache-{{ checksum "date" }}
          paths:
            - node_modules/
            - ../oppia_tools/

  lint_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Run lint tests
          command: |
            bash scripts/install_third_party.sh
            python scripts/third_party_size_check.py
            python scripts/pre_commit_linter.py --path=. --verbose
      - save_cache:
          key: third-party-cache-{{ checksum "date" }}
          paths:
            - third_party/

  frontend_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Run frontend tests
          command: |
            bash -x scripts/run_frontend_tests.sh --run-minified-tests=true
      - run:
          name: Generate frontend coverage report
          command: |
            sudo pip install codecov
            codecov --file ../karma_coverage_reports/coverage-final.json
          when: on_success

  backend_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Run backend tests
          command: |
            bash scripts/run_backend_tests.sh --generate_coverage_report --exclude_load_tests
      - run:
          name: Generate backend coverage report
          command: |
            sudo pip install codecov
            codecov
          when: on_success

  accessibility_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run accessibility e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="accessibility" --prod_env

  additionalEditorAndPlayerFeatures_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run additionalEditorAndPlayerFeatures e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="additionalEditorAndPlayerFeatures" --prod_env

  collections_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run collections e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="collections" --prod_env

  coreEditorAndPlayerFeatures_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run coreEditorAndPlayerFeatures e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="coreEditorAndPlayerFeatures" --prod_env

  embedding_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run embedding e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="embedding" --prod_env

  explorationFeedbackTab_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run explorationFeedbackTab e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="explorationFeedbackTab" --prod_env

  explorationHistoryTab_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run explorationHistoryTab e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="explorationHistoryTab" --prod_env

  explorationStatisticsTab_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run explorationStatisticsTab e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="explorationStatisticsTab" --prod_env

  explorationTranslationTab_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run explorationTranslationTab e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="explorationTranslationTab" --prod_env

  extensions_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run extensions e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="extensions" --prod_env

  learnerDashboard_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run learnerDashboard e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="learnerDashboard" --prod_env

  learner_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run learner e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="learner" --prod_env

  library_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run library e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="library" --prod_env

  navigation_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run navigation e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="navigation" --prod_env

  preferences_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run preferences e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="preferences" --prod_env

  profileMenu_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run profileMenu e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="profileMenu" --prod_env

  publication_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run publication e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="publication" --prod_env

  skillEditorPage_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run skillEditorPage e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="skillEditorPage" --prod_env

  subscriptions_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run subscriptions e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="subscriptions" --prod_env

  topicsAndSkillsDashboard_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run topicsAndSkillsDashboard e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="topicsAndSkillsDashboard" --prod_env

  topicAndStoryEditor_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run topicAndStoryEditor e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="topicAndStoryEditor" --prod_env

  users_e2e_tests:
    <<: *job_defaults
    steps:
      - checkout
      - run: date +%F > date
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_chrome
      - run:
          name: Run users e2e Tests
          command: |
            bash scripts/run_e2e_tests.sh --suite="users" --prod_env

workflows:
  version: 2
  circleci_tests:
    jobs:
      - setup
      # These lines are commented out because lint tests are being run on Travis CI.
      # - lint_tests:
      #     requires:
      #       - setup
      - frontend_tests:
         requires:
           - setup
      - backend_tests:
         requires:
           - setup
      - accessibility_e2e_tests:
          requires:
            - setup
      - additionalEditorAndPlayerFeatures_e2e_tests:
          requires:
            - setup
      - collections_e2e_tests:
          requires:
            - setup
      - coreEditorAndPlayerFeatures_e2e_tests:
          requires:
            - setup
      - embedding_e2e_tests:
          requires:
            - setup
      - explorationFeedbackTab_e2e_tests:
          requires:
            - setup
      - explorationHistoryTab_e2e_tests:
          requires:
            - setup
      - explorationStatisticsTab_e2e_tests:
          requires:
            - setup
      - explorationTranslationTab_e2e_tests:
          requires:
            - setup
      - extensions_e2e_tests:
          requires:
            - setup
      - learnerDashboard_e2e_tests:
          requires:
            - setup
      - learner_e2e_tests:
          requires:
            - setup
      - library_e2e_tests:
          requires:
            - setup
      - navigation_e2e_tests:
          requires:
            - setup
      - profileMenu_e2e_tests:
          requires:
            - setup
      - publication_e2e_tests:
          requires:
            - setup
      - skillEditor_e2e_tests:
          requires:
            - setup
      - subscriptions_e2e_tests:
          requires:
            - setup
      - topicsAndSkillsDashboard_e2e_tests:
          requires:
            - setup
      - topicAndStoryEditor_e2e_tests:
          requires:
            - setup
      - users_e2e_tests:
          requires:
            - setup

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/71ac71505d1d45161035
